### ISSUE TITLE
How to instrument Class side methods

### ISSUE THREAD

**Issue by mingle2** [jnunemaker/nunes#15]
I keep getting errors trying to instrument class side methods:

My class is set up like this:

class SearchInterface
 class << self

  def perform_search(search_conditions, options = {})
  end

  end
end

I set up Nunes and am doing the following:

require 'nunes'

class SearchInterface
 class << self
 extend Nunes::Instrumentable

  def perform_search(search_conditions, options = {})
  end

  end
end

undefined method `perform_search' for SearchInterface:Class (NoMethodError)

**Comment by jnunemaker** [comment]
Closing as old. If this is still an issue let me know and I'll open it up. I tend not to instrument class level stuff as most custom instrumentation is at the instance level.
