### ISSUE TITLE
Mobile Application Getting Weird Metrics

### ISSUE THREAD

**Issue by mingle2** [jnunemaker/nunes#16]
In my mobile rails 3 application I'm getting weird metrics like the following below. The issue that I'm having is that it seems nunes might be sending a new stats metric or rather unique stats metric for each request when it should be under a general controller method.  The problem is that backend graphing is dealing thousands of unique metrics but should really be 1 unique metric. Basically instead of tracking hundreds of metrics the graphing backend is tracking thousands of metrics (around 25K to be exact)

Weird controller metric:

mobile.action_controller.controller.FavoriteController.who_viewed_me.format.application.vnd.phonecom.mmc-xml

mobile.action_controller.controller.FavoriteController.who_viewed_me.format.application.octet-stream

These methods are invoked by ajax requests.  I think I'm getting a new statsd metric for every ajax request sent. They key is this dn.XXX extension... There should only be one metric being recorded.

mobile.action_controller.controller.FavoriteController.who_likes_me.format.dn.2546919457-5382d7fa
mobile.action_controller.controller.FavoriteController.who_likes_me.format.dn.4695030690-7a234f5a
mobile.action_controller.controller.FavoriteController.who_likes_me.format.dn.5337584390-2ec0a397

Any ideas on what the issue may be?

**Comment by jnunemaker** [comment]
I'm guessing this is due to this https://github.com/jnunemaker/nunes/blob/cb3aff0047b2b810279d6f705678c584dc465ffb/lib/nunes/subscribers/action_controller.rb#L20-L21. Whatever rails considers a validate format can go into statsd. Doesn't seem ideal. Maybe we should restrict acceptable formats?
