### ISSUE TITLE
increment not ending up whole numbers in graphite

### ISSUE THREAD

**Issue by wyaeld** [jnunemaker/nunes#20]
This has me stumped, but I don't know if the problem is nunes, statsd or graphite.  Maybe @jnunemaker knows.

nunes is plugged into a rails app with zero customization.  Graphite ends up with fractional counts, potentially 0.01 per hit.  Any idea why this might be?  Has me stumped currently, there are no formatting options in play, and Grafana shows the same.

![screenshot from 2015-12-10 15 58 43](https://cloud.githubusercontent.com/assets/157392/11705736/400dda2c-9f57-11e5-9f42-00dea5cb4ae2.png)

**Comment by jnunemaker** [comment]
I'm using nunes in production with no issues like this so my inclination is something with the version of statsd or graphite or graphite's retention period or something? I really don't know, but as I know of several installs working fine with nunes, I'm inclined to close this. If you find anything different, please let me know. Perhaps try nunes with datadog or instrumentalapp and see if you suffer the same issues there?
