### ISSUE TITLE
Version 0.5.0 not sending statsd for all controllers

### ISSUE THREAD

**Issue by dftaher** [jnunemaker/nunes#31]
I had to downgrade to 0.4.0 because I noticed updating the gem to 0.5.0 in rails 4.2.7.1 stopped sending statsd for all controllers specifically with namespace

**Comment by jnunemaker** [comment]
Sorry, somehow this slipped by me. The metric name for namespaced controllers changed, but they should still be reported. 

https://github.com/jnunemaker/nunes/compare/v0.4.0...v0.5.0#diff-02dd45c38e62ebdce27e2fd7944834b1R50

Any chance you can confirm or deny that is what happened?

**Comment by dftaher** [comment]
sorry, its been so long ago, I don't even remember, lot of things changed since then. Also it is possible i was using it differently. I'll close the ticket now, until i can reproduce it again. Thank you.
